LPS-189930
CaiocSiqueira/liferay-portal pull request #50
Opened 2023-07-13 17:35 UTC by CaiocSiqueira

2023-07-13 17:35 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-13 23:08 UTC, joshchong requested changes

2023-07-13 23:08 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/elasticsearch/Elasticsearch7.testcase
> +	test PerformConcurrentReindexUsingSidecarAndRemote {
Rename to `PerformConcurrentReindexAndSwitchElasticsearchConnections`

2023-07-13 23:08 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/elasticsearch/Elasticsearch7.testcase
> +		SystemSettings.saveConfiguration();
can remove this since it's already handled in `start-elasticsearch`

2023-07-14 17:27 UTC, CaiocSiqueira commented
ci:test:sf

2023-07-14 17:27 UTC, CaiocSiqueira commented
ci:test:search:nocompile

2023-07-14 17:27 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2023-07-14 17:32 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-14.liferay.com/job/test-portal-source-format/6349/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6349/jenkins-report.html">here</a>.</b></p>

2023-07-14 17:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 5 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f50159380194ca7b2bcd4b8cb54c7492680ef912">f50159380194ca7b2bcd4b8cb54c7492680ef912</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-189930">LPS-189930</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/9bd53e7765e673f107e0331364fb38107fb7fc1e">9bd53e7765e673f107e0331364fb38107fb7fc1e</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6349/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6349/jenkins-report.html">here</a>.</h5></details></html>

2023-07-14 17:39 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-14.liferay.com/job/test-portal-source-format/6349/">test-portal-source-format#6349</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-14.liferay.com/userContent/jobs/test-portal-source-format/builds/6349/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/CaiocSiqueira/liferay-portal/pull/50">CaiocSiqueira#50</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2382946566">[master] ci:test:sf - CaiocSiqueira &gt; CaiocSiqueira - PR#50 - 2023-07-14[10:30:27]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-14.liferay.com/job/publish-testray-report/3572/">publish-testray-report#3572</a><br/></div></div>

2023-07-14 18:07 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/7168/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7168/jenkins-report.html">here</a>.</b></p>

2023-07-14 19:31 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:search - 2 out of 2 jobs passed in 1 hour 24 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f50159380194ca7b2bcd4b8cb54c7492680ef912">f50159380194ca7b2bcd4b8cb54c7492680ef912</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/f50159380194ca7b2bcd4b8cb54c7492680ef912">f50159380194ca7b2bcd4b8cb54c7492680ef912</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2382211822">EE Development Acceptance (master) - 4687 - 2023-07-13[12:36:46]</a></p><details><summary><strong>ci:test:search - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/7168/">test-portal-acceptance-pullrequest(master)</a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/637077/">functional-tomcat90-mysql57-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7168/jenkins-report.html">here</a>.</h5></details></html>

2023-07-14 19:33 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-30.liferay.com/job/test-portal-acceptance-pullrequest(master)/7168/">test-portal-acceptance-pullrequest(master)#7168</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-30.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7168/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/CaiocSiqueira/liferay-portal/pull/50">CaiocSiqueira#50</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2383158300">[master] ci:test:search - CaiocSiqueira &gt; CaiocSiqueira - PR#50 - 2023-07-14[11:06:31]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-30.liferay.com/job/publish-testray-report/17755/">publish-testray-report#17755</a><br/></div></div>

2023-07-14 21:53 UTC, joshchong commented
Forwarding here:
https://github.com/joshchong/liferay-portal/pull/767

2023-07-21 14:15 UTC, closed without merging