LPS-188558
CaiocSiqueira/liferay-portal pull request #55
Opened 2023-07-31 18:15 UTC by CaiocSiqueira

https://liferay.atlassian.net/browse/LPS-188558

2023-07-31 18:15 UTC, liferay-continuous-integration commented
To conserve resources, the PR Tester does not automatically run for every pull.

If your code changes were already tested in another pull, reference that pull in this pull so the test results can be analyzed.

If your pull was never tested, comment &quot;ci:test&quot; to run the PR Tester for this pull.

2023-07-31 18:15 UTC, CaiocSiqueira commented
ci:test:sf

2023-07-31 18:16 UTC, CaiocSiqueira commented
ci:test:search-solr:nocompile

2023-07-31 18:16 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2023-07-31 18:17 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-40.liferay.com/job/test-portal-source-format/2356/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2356/jenkins-report.html">here</a>.</b></p>

2023-07-31 18:20 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/6788ad965784d2fe7b477380b8f50047e8c73775">6788ad965784d2fe7b477380b8f50047e8c73775</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-188558">LPS-188558</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/16f8a9fc1ddc67a7677822adae3752b5733d4942">16f8a9fc1ddc67a7677822adae3752b5733d4942</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2356/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2356/jenkins-report.html">here</a>.</h5></details></html>

2023-07-31 18:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-40.liferay.com/job/test-portal-source-format/2356/">test-portal-source-format#2356</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-40.liferay.com/userContent/jobs/test-portal-source-format/builds/2356/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/CaiocSiqueira/liferay-portal/pull/55">CaiocSiqueira#55</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2397459930">[master] ci:test:sf - CaiocSiqueira &gt; CaiocSiqueira - PR#55 - 2023-07-31[11:16:03]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-40.liferay.com/job/publish-testray-report/8649/">publish-testray-report#8649</a><br/></div></div>

2023-07-31 18:42 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search-solr</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1150/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1150/jenkins-report.html">here</a>.</b></p>

2023-07-31 20:50 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search-solr - 0 out of 2 jobs passed in 2 hours 8 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e3f2d6fab9527fd6b7ed250d3ca110930e49fa00">e3f2d6fab9527fd6b7ed250d3ca110930e49fa00</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e3f2d6fab9527fd6b7ed250d3ca110930e49fa00">e3f2d6fab9527fd6b7ed250d3ca110930e49fa00</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2397326372">EE Development Acceptance (master) - 4716 - 2023-07-31[04:37:17]</a></p><details><summary><strong>ci:test:search-solr - 0 out of 2 jobs PASSED</strong></summary><div><h4>2 Failed Jobs:</h4><ul><li><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1150/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/243536/"><strike>functional-tomcat90-mysql57-jdk8/0/0</strike></a></li></ul></li></ul></div></details><h5>For more details click <a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1150/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/243536//consoleText">functional-tomcat90-mysql57-jdk8/0/0</a><ol><li><div><a href="https://test-1-15.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/243536//testReport/com.liferay.poshi.runner/PoshiRunner/test_LocalFile_SolrSearch_ConcurrentReindexExecutionModeNotAvailableForSolr_">LocalFile.SolrSearch#ConcurrentReindexExecutionModeNotAvailableForSolr</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-07/test-1-32/test-portal-acceptance-pullrequest(master)/1150/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SolrSearch_ConcurrentReindexExecutionModeNotAvailableForSolr/index.html.gz">Poshi Report</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-07/test-1-32/test-portal-acceptance-pullrequest(master)/1150/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SolrSearch_ConcurrentReindexExecutionModeNotAvailableForSolr/summary.html.gz">Poshi Summary</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-07/test-1-32/test-portal-acceptance-pullrequest(master)/1150/functional-tomcat90-mysql57-jdk8/0/0/LocalFile.SolrSearch_ConcurrentReindexExecutionModeNotAvailableForSolr/console.txt.gz">Poshi Console</a> - <a href="https://testray.liferay.com/reports/production/logs/2023-07/test-1-32/test-portal-acceptance-pullrequest(master)/1150/functional-tomcat90-mysql57-jdk8/0/0/jenkins-console.txt.gz">Console Output</a></div></li></ol></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-07-31 20:53 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-32.liferay.com/job/test-portal-acceptance-pullrequest(master)/1150/">test-portal-acceptance-pullrequest(master)#1150</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-32.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/1150/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search-solr<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/CaiocSiqueira/liferay-portal/pull/55">CaiocSiqueira#55</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2397534201">[master] ci:test:search-solr - CaiocSiqueira &gt; CaiocSiqueira - PR#55 - 2023-07-31[11:41:46]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-32.liferay.com/job/publish-testray-report/25619/">publish-testray-report#25619</a><br/></div></div>

2023-08-02 17:36 UTC, joshchong requested changes

2023-08-02 17:36 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SolrSearch.testcase
> +	test ConcurrentReindexExecutionModeNotAvailableForSolr {
Rename to `ConcurrentReindexNotAvailableOnSolr`

2023-08-02 17:36 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SolrSearch.testcase
> +		}
Can remove this assertion.

2023-08-02 17:36 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SolrSearch.testcase
> +	test ConcurrentReindexExecutionModeNotAvailableForSolr {
Move entire test to Solr.testcase as that file is more appropriate for Solr specific use cases. SolrSearch.testcase is for use cases that are also relevant with Elasticsearch, but is just specifically tested on Solr

2023-08-02 17:36 UTC, joshchong commented on portal-web/test/functional/com/liferay/portalweb/tests/coreinfrastructure/search/searchportlet/SolrSearch.testcase
> +				radioLabel = "All Instances");
Can remove this

2023-08-03 17:11 UTC, CaiocSiqueira commented
ci:test:sf

2023-08-03 17:12 UTC, CaiocSiqueira commented
ci:test:search-solr:nocompile

2023-08-03 17:13 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2023-08-03 17:38 UTC, liferay-continuous-integration commented
<html><h3>:x: ci:test:search-solr - 0 out of 1 jobs passed in 2 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dd672313a69fa5c86d77d2999c0e53a64e77bd8d">dd672313a69fa5c86d77d2999c0e53a64e77bd8d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/e3f2d6fab9527fd6b7ed250d3ca110930e49fa00">e3f2d6fab9527fd6b7ed250d3ca110930e49fa00</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2397326372">EE Development Acceptance (master) - 4716 - 2023-07-31[04:37:17]</a></p><details><summary><strong>ci:test:search-solr - 0 out of 1 jobs PASSED</strong></summary><div><h4>1 Failed Jobs:</h4><ul><li><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7799/"><strike>test-portal-acceptance-pullrequest(master)</strike></a></li></ul></div></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7799/jenkins-report.html">here</a>.</h5><hr/><h4>Failures unique to this pull:</h4><ol><li><div><h5><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7799/">test-portal-acceptance-pullrequest(master)</a></h5><div><h6>Job Results:</h6><p>0 Jobs Passed.<br/>1 Job Failed.</p></div><div><p>Please fix <strong>rebase errors</strong> on <strong><a href="https://github.com/CaiocSiqueira/liferay-portal/pull/55">CaiocSiqueira/LPS-188558</a></strong><pre>Unable to rebase master-temp-1691084285058 to master
Rebasing (1/2)
Rebasing (2/2)
error: could not apply e6369e39f6bb... LPS-188558 DO NOT MERGE
Resolve all conflicts manually, mark them as resolved with
"git add/rm &lt;conflicted_files&gt;", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
Could not apply e6369e39f6bb... LPS-188558 DO NOT MERGE</pre></p></div></div></li></ol><h4>For upstream results, click <a href="https://test-1-1.liferay.com/job/test-portal-acceptance-upstream-dxp(master)">here</a>.</h4></details></html>

2023-08-03 18:08 UTC, CaiocSiqueira commented
ci:test:sf

2023-08-03 18:16 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-5.liferay.com/job/test-portal-source-format/5811/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5811/jenkins-report.html">here</a>.</b></p>

2023-08-03 18:18 UTC, CaiocSiqueira commented
ci:test:search-solr:nocompile

2023-08-03 18:18 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2023-08-03 18:19 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 4 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/57601959e7a4e39676bf8064321af055e6ce24ea">57601959e7a4e39676bf8064321af055e6ce24ea</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-188558">LPS-188558</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/b4ce2affbdd4f98965e215954d7f1cdbe4f9b43c">b4ce2affbdd4f98965e215954d7f1cdbe4f9b43c</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5811/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5811/jenkins-report.html">here</a>.</h5></details></html>

2023-08-03 18:22 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-5.liferay.com/job/test-portal-source-format/5811/">test-portal-source-format#5811</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-5.liferay.com/userContent/jobs/test-portal-source-format/builds/5811/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/CaiocSiqueira/liferay-portal/pull/55">CaiocSiqueira#55</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2399623640">[master] ci:test:sf - CaiocSiqueira &gt; CaiocSiqueira - PR#55 - 2023-08-03[11:14:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-5.liferay.com/job/publish-testray-report/2332/">publish-testray-report#2332</a><br/></div></div>

2023-08-03 18:39 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search-solr</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7800/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7800/jenkins-report.html">here</a>.</b></p>

2023-08-03 18:53 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:search-solr - 1 out of 1 jobs passed in 14 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dd672313a69fa5c86d77d2999c0e53a64e77bd8d">dd672313a69fa5c86d77d2999c0e53a64e77bd8d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8cd8a57f729c9e7b8b7a2dd1ef56c52b78c8ba95">8cd8a57f729c9e7b8b7a2dd1ef56c52b78c8ba95</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2398848571">EE Development Acceptance (master) - 4723 - 2023-08-02[08:43:07]</a></p><details><summary><strong>ci:test:search-solr - 1 out of 1 jobs PASSED</strong></summary></details><h5>For more details click <a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7800/jenkins-report.html">here</a>.</h5></details></html>

2023-08-03 18:55 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-29.liferay.com/job/test-portal-acceptance-pullrequest(master)/7800/">test-portal-acceptance-pullrequest(master)#7800</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-29.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/7800/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search-solr<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/CaiocSiqueira/liferay-portal/pull/55">CaiocSiqueira#55</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2399638510">[master] ci:test:search-solr - CaiocSiqueira &gt; CaiocSiqueira - PR#55 - 2023-08-03[11:38:49]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-29.liferay.com/job/publish-testray-report/17750/">publish-testray-report#17750</a><br/></div></div>

2023-08-03 19:02 UTC, CaiocSiqueira commented
ci:test:sf

2023-08-03 19:02 UTC, CaiocSiqueira commented
ci:test:search-solr:nocompile

2023-08-03 19:02 UTC, liferay-continuous-integration commented
The test will run with a prebuilt bundle.

2023-08-03 19:04 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>search-solr</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/6476/">test-portal-acceptance-pullrequest(master)</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6476/jenkins-report.html">here</a>.</b></p>

2023-08-03 19:05 UTC, liferay-continuous-integration commented
<h1>Build started.</h1><p>Jenkins is currently running tests in the <code>sf</code> test suite.</p><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a></p><h4>Job Summary:</h4><p>Job Link: <a href="https://test-1-39.liferay.com/job/test-portal-source-format/3635/">test-portal-source-format</a></p><p><b>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3635/jenkins-report.html">here</a>.</b></p>

2023-08-03 19:09 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:sf - 1 out of 1 jobs passed in 7 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/57601959e7a4e39676bf8064321af055e6ce24ea">57601959e7a4e39676bf8064321af055e6ce24ea</a></p><h4>Sender Branch:</h4><p>Branch Name: <a href="https://github.com/CaiocSiqueira/liferay-portal/tree/LPS-188558">LPS-188558</a><br/>Branch GIT ID: <a href="https://github.com/CaiocSiqueira/liferay-portal/commit/0bff045c8d95bc870cd62eb1a2fb0dd05fda7700">0bff045c8d95bc870cd62eb1a2fb0dd05fda7700</a></p>1 out of 1jobs PASSED<details><summary><strong>1 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3635/">test-portal-source-format</a></li></ul></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3635/jenkins-report.html">here</a>.</h5></details></html>

2023-08-03 19:16 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-source-format/3635/">test-portal-source-format#3635</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-source-format/builds/3635/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>sf<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/CaiocSiqueira/liferay-portal/pull/55">CaiocSiqueira#55</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2399709910">[master] ci:test:sf - CaiocSiqueira &gt; CaiocSiqueira - PR#55 - 2023-08-03[12:02:30]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/13341/">publish-testray-report#13341</a><br/></div></div>

2023-08-03 19:35 UTC, liferay-continuous-integration commented
<html><h3>:heavy_check_mark: ci:test:search-solr - 2 out of 2 jobs passed in 31 minutes</h3><details><summary>Click here for more details.</summary><h4>Base Branch:</h4><p>Branch Name: <a href="https://github.com/liferay/liferay-portal/tree/master">master</a><br/>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/dd672313a69fa5c86d77d2999c0e53a64e77bd8d">dd672313a69fa5c86d77d2999c0e53a64e77bd8d</a></p><h4>Upstream Comparison:</h4><p>Branch GIT ID: <a href="https://github.com/liferay/liferay-portal/commit/8cd8a57f729c9e7b8b7a2dd1ef56c52b78c8ba95">8cd8a57f729c9e7b8b7a2dd1ef56c52b78c8ba95</a><br/>Jenkins Build URL: <a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2398848571">EE Development Acceptance (master) - 4723 - 2023-08-02[08:43:07]</a></p><details><summary><strong>ci:test:search-solr - 2 out of 2 jobs PASSED</strong></summary><details><summary><strong>2 Successful Jobs:</strong></summary><ul><li><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/6476/">test-portal-acceptance-pullrequest(master)</a></li><li>functional-tomcat90-mysql57-jdk8<ul><li><a href="https://test-1-26.liferay.com/job/test-portal-acceptance-pullrequest-downstream(master)/741998/">functional-tomcat90-mysql57-jdk8/0/0</a></li></ul></li></ul></details></details><h5>For more details click <a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6476/jenkins-report.html">here</a>.</h5></details></html>

2023-08-03 19:37 UTC, liferay-continuous-integration commented
<div><div><strong>Jenkins Build:</strong><span></span><a href="https://test-1-39.liferay.com/job/test-portal-acceptance-pullrequest(master)/6476/">test-portal-acceptance-pullrequest(master)#6476</a><br/></div><div><strong>Jenkins Report:</strong><span></span><a href="https://test-1-39.liferay.com/userContent/jobs/test-portal-acceptance-pullrequest(master)/builds/6476/jenkins-report.html">jenkins-report.html</a><br/></div><div><strong>Jenkins Suite:</strong><span></span>search-solr<br/></div><div><strong>Pull Request:</strong><span></span><a href="https://github.com/CaiocSiqueira/liferay-portal/pull/55">CaiocSiqueira#55</a><br/></div><div><strong>Testray Routine:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/builds?testrayRoutineId=1306753894">EE Pull Request</a><br/></div><div><strong>Testray Build:</strong><span></span><a href="https://testray.liferay.com/home/-/testray/runs?testrayBuildId=2399721703">[master] ci:test:search-solr - CaiocSiqueira &gt; CaiocSiqueira - PR#55 - 2023-08-03[12:04:00]</a><br/></div><div><strong>Testray Importer:</strong><span></span><a href="https://test-1-39.liferay.com/job/publish-testray-report/13345/">publish-testray-report#13345</a><br/></div></div>

2023-08-04 18:38 UTC, closed without merging